name: benchmark results

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v2
    - name: Install hyperfine
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_amd64.deb
        sudo dpkg -i hyperfine_1.12.0_amd64.deb

    - name: Run benchmark script
      run: ./benchmark.sh all

    - name: Add disclaimer
      run: echo "These tests were run on GitHub CI which has lower performance than running locally. Usually local times are 2x faster" >> results.md

    - name: Commit and push changes
      run: |
        git config --global user.name "Benchmark bot"
        git config --global user.email "benchmarks@bot.com"
        git add results.md
        git commit -m "Update benchmark results"
        git push
