name: benchmark results

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v2

    - name: Install hyperfine
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_amd64.deb
        sudo dpkg -i hyperfine_1.12.0_amd64.deb

    - name: Install valgrind
      run: sudo apt install valgrind

    - name: Run hyperfine benchmark
      run: |
        ./benchmark.sh hyperfine all
        echo -e "\nThese tests were run on GitHub CI which has lower performance than running locally. Local times are around 2x faster" >> results.md

    - name: Run iai benchmark
      run: ./benchmark.sh iai > iai_results.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "benchmark bot"
        git config --global user.email "benchmarks@bot.com"
        git add results.md iai_results.txt
        git commit -m "Update benchmark results"
        git push
